import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import KeyWatcher from "./components/logic/keyWatcher";
import "./globals.css";
import Cursor from "../app/components/cursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const boska = localFont({
  src: [
    {
      path: "../public/fonts/Boska-Variable.woff2",
      style: "normal",
      weight: "100 900",
    },
    {
      path: "../public/fonts/Boska-VariableItalic.woff2",
      style: "italic",
      weight: "100 900",
    },
  ],
  variable: "--font-boska",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${boska.variable} antialiased`}
        suppressHydrationWarning
      >
        <Cursor />
        <KeyWatcher />
        {children}
      </body>
    </html>
  );
}
